# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatBoatSwiftAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "ReverseExtension"

  target 'ChatBoatSwiftAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatBoatSwiftAIUITests' do
    # Pods for testing
  end

end
